Fix error related to missing attributes
It fixes the error about missing attributes in CRF class.

  AttributeError: 'CRF' object has no attribute 'keep_tempfiles'
  AttributeError: 'CRF' object has no attribute 'model_filename'